- hosts: all
  # No-op task to set ansible_env (see https://github.com/ansible/ansible/issues/14655)

- hosts: all
  vars:
    repos:
      - vim-config

  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

  tasks:
    - import_tasks: sudo.yml

    - name: Install Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null
      args:
        creates: /usr/local/bin/brew

    - name: Tap Homebrew Bundle
      homebrew_tap: tap=Homebrew/bundle

    - import_tasks: sudo.yml
    - file:
        path: /usr/local/Caskroom
        state: directory
        owner: "{{ ansible_user_id }}"
        group: staff
      become: yes

    - name: Install from the Brewfile
      command: brew bundle
      args:
        chdir: ~/workspace/workstation-setup
      ignore_errors: yes

    - name: Update repos
      git:
        repo: https://github.com/sentientmonkey/{{ item }}.git
        dest: ~/workspace/{{ item }}
      ignore_errors: yes # Ignore dirty repos
      with_items: "{{ repos }}"

    - name: Symlink child repositories
      file: src=~/workspace/{{ item.key }} dest={{ item.value }} state=link
      with_dict:
        vim-config: ~/.vim
        vim-config/vimrc: ~/.vimrc

    - name: install vim
      command: bin/install
      args:
        chdir: ~/workspace/vim-config

    - name: Make vim use MacVim
      file: src=/Applications/MacVim.app/Contents/bin/mvim dest=/usr/local/bin/vim state=link

    - name: oh my zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: ~/.oh-my-zsh

    - name: Symlink config files
      file: src=~/workspace/workstation-setup/dotfiles/{{ item }} dest=~/{{ item }} state=link
      with_items:
        - .git_templates
        - .gitconfig
        - .gitignore_global

    - name: Update OS X defaults
      osx_defaults:
        domain: "{{ item.domain | default(omit) }}"
        key: "{{ item.key }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
      with_items:
        - # Autohide the Dock
          domain: com.apple.dock
          key: autohide
          type: bool
          value: true
        - # Put the Dock on the left
          domain: com.apple.dock
          key: orientation
          type: string
          value: left
        - # don't use natural scrolling
          domain: NSGlobalDomain
          key: com.apple.swipescrolldirection
          type: bool
          value: false

    - name: Install dockutil
      homebrew: name=dockutil
    - name: Remove all icons from the Dock
      command: dockutil --remove all
    - name: Add /Applications/ to the Dock
      command: dockutil --add /Applications/ --sort name
    - name: Restart the Dock
      command: killall Dock
      ignore_errors: yes

- import_playbook: ssh.yml
